openapi: 3.0.3
info:
  title: Filmorete API Documentation
  description: |-
    Тут будет описание
  version: 1.0.11
servers:
  - url: http://localhost:8080
tags:
  - name: Films
    description: Тут будет описание категории запросов
paths:
  /films/{id}:
    get:
      tags:
        - Films
      summary: Тут будет описание запроса
      description: еще одно описание
      operationId: getFilmById
      parameters:
        - name: id
          in: path
          description: id фильма.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getFilmBiId_200'          
        '404':
          description: Film not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getFilmBiId_404' 

  
components:
  schemas:
    getFilmBiId_200:
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Saturday Night Fever
        description: 
          type: string
          example: It Is Now Rated PG Because we want everyone to see John Travolta's performance... Because we want everyone to hear the 1 group in the country, the Bee Gees... Because we want everyone to catch 'Saturday Night Fever
        releaseDate:
          type: string
          example: 1977-12-12
        duration:
          type: integer
          format: int64
          example: 118
        likes:
          type: array
          items:
            type: integer
            format: int64
            example: 1
    getFilmBiId_404:
      properties:
        errors:
          type: array
          items:
            type: string
            example: '[id] film with this id does not exist'
